import { v4 as uuidv4 } from 'uuid';
import {
  Block,
  BlockShape,
  BlockState,
  BlockType,
  BooleanValue,
  ComparisonOperator,
  LogicalOperator,
  MathOperator,
} from '../blocks/types';

const workbenchBlocks: Block[] = [
  // Variables
  {
    id: uuidv4(),
    type: BlockType.Variable,
    shape: BlockShape.Square,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    selected: 'x',
    parentId: null,
    prevId: null,
    nextId: null,
    children: {
      expression: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.VariableValue,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    selected: 'x',
    parentId: null,
    prevId: null,
    nextId: null,
    children: null,
  },

  // Conditionals
  {
    id: uuidv4(),
    type: BlockType.If,
    shape: BlockShape.Square,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    children: {
      condition: [],
      body: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.Elif,
    shape: BlockShape.Square,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    children: {
      condition: [],
      body: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.Else,
    shape: BlockShape.Square,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    children: {
      body: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.IfElse,
    shape: BlockShape.Square,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    children: {
      condition: [],
      ifBody: [],
      elseBody: [],
    },
  },

  // Loops
  {
    id: uuidv4(),
    type: BlockType.For,
    shape: BlockShape.Square,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    children: {
      expression: [],
      body: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.While,
    shape: BlockShape.Square,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    children: {
      condition: [],
      body: [],
    },
  },

  // Values
  {
    id: uuidv4(),
    type: BlockType.Number,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    value: '',
    children: null,
  },
  {
    id: uuidv4(),
    type: BlockType.String,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    value: '',
    children: null,
  },
  {
    id: uuidv4(),
    type: BlockType.Boolean,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    value: BooleanValue.True,
    children: null,
  },

  // Maths
  {
    id: uuidv4(),
    type: BlockType.Math,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    operator: MathOperator.Addition,
    children: {
      left: [],
      right: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.Math,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    operator: MathOperator.Subtraction,
    children: {
      left: [],
      right: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.Math,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    operator: MathOperator.Multiplication,
    children: {
      left: [],
      right: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.Math,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    operator: MathOperator.Division,
    children: {
      left: [],
      right: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.Math,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    operator: MathOperator.Modulo,
    children: {
      left: [],
      right: [],
    },
  },

  // Comparisons
  {
    id: uuidv4(),
    type: BlockType.Comparison,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    operator: ComparisonOperator.Equal,
    children: {
      left: [],
      right: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.Comparison,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    operator: ComparisonOperator.NotEqual,
    children: {
      left: [],
      right: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.Comparison,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    operator: ComparisonOperator.GreaterThan,
    children: {
      left: [],
      right: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.Comparison,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    operator: ComparisonOperator.LessThan,
    children: {
      left: [],
      right: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.Comparison,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    operator: ComparisonOperator.GreaterThanOrEqual,
    children: {
      left: [],
      right: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.Comparison,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    operator: ComparisonOperator.LessThanOrEqual,
    children: {
      left: [],
      right: [],
    },
  },

  // Logic
  {
    id: uuidv4(),
    type: BlockType.Logical,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    operator: LogicalOperator.And,
    children: {
      left: [],
      right: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.Logical,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    operator: LogicalOperator.Or,
    children: {
      left: [],
      right: [],
    },
  },
  {
    id: uuidv4(),
    type: BlockType.Logical,
    shape: BlockShape.Round,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    operator: LogicalOperator.Not,
    children: {
      operand: [],
    },
  },

  // Output
  {
    id: uuidv4(),
    type: BlockType.Print,
    shape: BlockShape.Square,
    coords: { x: 0, y: 0 },
    isWorkbenchBlock: true,
    state: BlockState.Idle,
    parentId: null,
    prevId: null,
    nextId: null,
    children: {
      expression: [],
    },
  },
];

// This is a simple way to have categories in the workbench. Make sure the indeces
// are correct
export const blockCategories = {
  Variables: [0, 1],
  Conditionals: [2, 3, 4, 5],
  Loops: [6, 7],
  Values: [8, 9, 10],
  Maths: [11, 12, 13, 14, 15],
  Comparisons: [16, 17, 18, 19, 20, 21],
  Logic: [22, 23, 24],
  Output: [25],
};

export default workbenchBlocks;
